# Generated by Django 5.1.6 on 2025-03-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
        migrations.AddField(
            model_name='table',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
