# Generated by Django 5.2.1 on 2025-05-09 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_category_alter_ad_options_ad_is_active_ad_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ad',
            name='contact',
            field=models.CharField(default='Не указано', max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
