# Generated by Django 5.2.1 on 2025-05-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_ad_options_remove_ad_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='short_description',
            field=models.TextField(default='Нет краткого описания'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
